//! Recommended default pipelines, keyed by input file type.
//!
//! The graphs themselves are data: `assets/default.<i-*>.graph` holds each
//! family's serialized default pipeline (the display graph the editor opens),
//! compiled into the binary by `build.zig`. This table only maps file
//! extensions to a family, and building a graph deserializes that family's
//! asset before applying the caller's options — so supporting a decoder is one
//! asset plus one row here, not another chain of `addModule` calls.

const std = @import("std");
const api = @import("modules/api.zig");
const pipeline = @import("pipeline.zig");
const serdes = @import("serdes.zig");

/// One decodable input family.
pub const Format = struct {
    /// The `i-*` module that reads the file; also identifies the family and
    /// names its asset, `assets/default.<source_module>.graph`.
    source_module: []const u8,
    /// File extensions this family claims, without the leading dot.
    extensions: []const []const u8,
    /// The serialized default graph, embedded by `build.zig`. Its shape is
    /// whatever the serializer emits for that family's display pipeline, so it
    /// can be regenerated by serializing a live pipeline.
    graph: []const u8,
};

/// Every input family the engine decodes.
const formats = [_]Format{
    .{
        .source_module = "i-raw",
        .extensions = &.{
            "nef", "cr2", "cr3", "arw", "dng", "raf", "rw2", "orf", "pef", "srw", "nrw", "raw",
        },
        .graph = @embedFile("default.i-raw.graph"),
    },
    .{
        .source_module = "i-png",
        .extensions = &.{"png"},
        .graph = @embedFile("default.i-png.graph"),
    },
};

/// The family that decodes `path`, judged from its extension alone; null when
/// no `i-*` module claims it.
pub fn formatForPath(path: []const u8) ?*const Format {
    const ext = std.fs.path.extension(path);
    if (ext.len < 2) return null;
    const bare = ext[1..]; // skip the dot
    for (&formats) |*format| {
        for (format.extensions) |candidate| {
            if (std.ascii.eqlIgnoreCase(bare, candidate)) return format;
        }
    }
    return null;
}

pub const Options = struct {
    /// When set, a `downscale` module caps the longest edge of the output. The
    /// editor passes null (full resolution); the thumbnail decoder passes the
    /// catalog's thumbnail size.
    max_edge: ?u32 = null,
    /// When set, the graph ends in a file sink writing to this path instead of
    /// its `o-display` sink. The thumbnail decoder uses this to render into its
    /// on-disk cache.
    output_path: ?[]const u8 = null,
    /// File sink module used for `output_path`. Any `o-*` module with an
    /// rgba16float input and a `filename` param works (`o-png`, `o-qoi`, ...).
    output_module: []const u8 = "o-png",
};

/// The endpoints of a recommended graph. `sink` is the asset's `o-display`
/// sink unless `Options.output_path` asked for a file sink; callers that render
/// repeatedly can re-point the sink's `filename` param without rebuilding the
/// graph.
pub const Graph = struct {
    source: pipeline.ModuleHandle,
    sink: pipeline.ModuleHandle,
};

/// Build the recommended pipeline for `path` and point its source at the file.
pub fn recommend(
    pipe: *pipeline.Pipeline,
    path: []const u8,
    options: Options,
) !Graph {
    const format = formatForPath(path) orelse return error.UnsupportedFileType;
    const graph = try recommendFormat(pipe, format, options);
    try pipe.setModuleParam(graph.source, "filename", []const u8, path);
    return graph;
}

/// Build the graph `format.graph` describes, then apply `options` to its tail:
/// `max_edge` inserts a `downscale` before the sink, `output_path` swaps the
/// display sink for a file sink. The source's `filename` param is left for the
/// caller to set (e.g. to decode many files through one cached pipeline).
pub fn recommendFormat(
    pipe: *pipeline.Pipeline,
    format: *const Format,
    options: Options,
) !Graph {
    // A graph is configuration, not an edit: it is applied through serdes'
    // non-recording primitives, exactly like `Pipeline.clear`.
    try serdes.deserialize(pipe, format.graph);

    const source = try moduleOfType(pipe, .source);
    const display = try moduleOfType(pipe, .sink);
    if (options.output_path == null and options.max_edge == null) {
        return .{ .source = source, .sink = display };
    }

    // The display sink is the end of the asset's chain: everything appended
    // hangs off what feeds it.
    var tail = try upstream(pipe, display);
    var sink = display;
    if (options.output_path != null) {
        sink = try swapSink(pipe, display, options.output_module);
    }
    if (options.max_edge) |max_edge| {
        tail = try appendDownscale(pipe, tail, max_edge);
    }
    try connectNoRecord(pipe, tail, sink, "input");
    if (options.output_path) |path| {
        try pipe.setModuleParam(sink, "filename", []const u8, path);
    }
    return .{ .source = source, .sink = sink };
}

/// The graph's one module of `kind`. Module types are the graph's own
/// vocabulary, so the endpoints need no naming convention.
fn moduleOfType(pipe: *pipeline.Pipeline, kind: api.ModuleType) !pipeline.ModuleHandle {
    var it = pipe.module_pool.liveHandles();
    while (it.next()) |handle| {
        const mod = try pipe.module_pool.getPtr(handle);
        if (mod.type == kind) return handle;
    }
    return error.GraphModuleMissing;
}

/// A module handle plus the name of one of its sockets.
const Link = struct { module: pipeline.ModuleHandle, socket: []const u8 };

/// What feeds the input of `dst`.
fn upstream(pipe: *pipeline.Pipeline, dst: pipeline.ModuleHandle) !Link {
    const mod = try pipe.module_pool.getPtr(dst);
    for (mod.sockets) |maybe| {
        const sock = maybe orelse continue;
        if (sock.type.direction() != .input) continue;
        const conn = sock.connected_to_module orelse continue;
        const src = try pipe.module_pool.getPtr(conn.item);
        const src_sock = src.sockets[conn.socket_idx] orelse continue;
        return .{ .module = conn.item, .socket = src_sock.name };
    }
    return error.GraphSinkMissingInput;
}

/// Replace the graph's `sink` with `module`, returning the new sink.
fn swapSink(pipe: *pipeline.Pipeline, sink: pipeline.ModuleHandle, module: []const u8) !pipeline.ModuleHandle {
    const display = try pipe.module_pool.getPtr(sink);
    try pipe.removeModuleByNameNoRecord(display.name, display.id);
    return pipe.addModuleNoRecord("01", module);
}

/// Append a `downscale` capping the longest edge, returning the new tail.
fn appendDownscale(pipe: *pipeline.Pipeline, tail: Link, max_edge: u32) !Link {
    const downscale = try pipe.addModuleNoRecord("01", "downscale");
    try pipe.setModuleParam(downscale, "max_edge", i32, @intCast(max_edge));
    try connectNoRecord(pipe, tail, downscale, "input");
    return .{ .module = downscale, .socket = "output" };
}

/// Connect two modules without touching the history (see `recommendFormat`).
fn connectNoRecord(pipe: *pipeline.Pipeline, src: Link, dst: pipeline.ModuleHandle, dst_socket: []const u8) !void {
    const src_mod = try pipe.module_pool.getPtr(src.module);
    const dst_mod = try pipe.module_pool.getPtr(dst);
    try pipe.connectModulesByNameNoRecord(src_mod.name, src_mod.id, src.socket, dst_mod.name, dst_mod.id, dst_socket);
}
